export const boxes = [
  { name: "Javascript", image: "icon-javascript.svg" },
  { name: "Typescript", image: "icon-typescript.svg" },
  { name: "React", image: "icon-react.svg" },
  { name: "Next.js", image: "icon-nextjs.svg" },
  { name: "Node.js", image: "icon-nodejs.svg" },
  { name: "Express.js", image: "icon-express.svg" },
  { name: "Nest.js", image: "icon-nest.svg" },
  { name: "Socket.io", image: "icon-socket.svg" },
  { name: "PostgreSQL", image: "icon-postgresql.svg" },
  { name: "MongoDB", image: "icon-mongodb.svg" },
  { name: "Sass/Scss", image: "icon-sass.svg" },
  { name: "Tailwindcss", image: "icon-tailwindcss.svg" },
  { name: "Figma", image: "icon-figma.svg" },
  { name: "Cypress", image: "icon-cypress.svg" },
  { name: "Storybook", image: "icon-storybook.svg" },
  { name: "Git", image: "icon-git.svg" },
];
